### ISSUE TITLE
Soulseek installation not working

### ISSUE THREAD

**Issue by andreifilip** [danielguerra69/soulseek#1]
Hi Daniel,

First, thanks a lot for this nice image.
I've just installed this on my Synology DS412+ and it's working perfect on my 2GB

The issue that I'm having is that cannot install Soulseek
The right click doesn't do anything, and when I've tried to run the soulseek_install command it prompts me for a password. I think this is the problem. 

Thanks

**Comment by danielguerra69** [comment]
Hi Andrei,

I know heard it, checked openbox rc.xml it says right click. I use a mac
and just use two finger click (e.g. right click) 
I am working on a unattended install right now with winetricks.
In a few days it will sure be up and running.
I tested it in a virtualbox on a mac. It is for a friend with a synology.
You can make it work if you can do something on the commandline
of your syno e.g. docker exec -ti soulseek /bin/bash
then
wine /bin/Soul<tab>

I let you know when its complete.

Regards,

Daniel

**Comment by andreifilip** [comment]
Hi Daniel,

Thanks a lot for you quick answer. 

I'm also a mac user too...;)

Yeah, I guess I was misleading you, and really sorry for that
What I wanted to say about right click is that when I right click and and press Install Soulseek nothing happens...that's what I meant, again sorry for that...

I will try the commands line you told me about.

What I have tried is using the CL from the soulseek virtualization itself, and that's when I got prompted for the password (sudo-er related, I guess)

Again,
Many thanks

**Comment by danielguerra69** [comment]
The quick workaround is use the xterm from the menu.
Then type
/bin/bash
wine /bin/SoulseekQt-2015-6-12.exe

**Comment by andreifilip** [comment]
Hi Daniel,

Thanks. 

Now it worked installing, but I was also prompted to install MONO and Gecko
Then I had to go to the installation folder
~/.wine/drive_c/Program Files (x86)/SoulseekQT and run it with 
wine SoulseekQT.exe

The right click -> Start Soulseek still doesn't work, but at this stage its fine for me.
Let me know if you have an update for this minor issue

P.S.
Why did you choose to run Soulseek with wine? Isn't there a LINUX distros for this ?

Thanks a lot

**Comment by danielguerra69** [comment]
Hi,

Just placed an update, install and program should start automatic

Regards,

Daniel

**Comment by andreifilip** [comment]
Great Daniel,

Thanks a lot

Cheers...:)
